miky_user_admin_employee_security_login:
    path:      /login
    defaults:  { _controller: MikyUserBundle:Admin/Security:login }

miky_user_admin_employee_security_logout:
    path:      /logout
    defaults:  { _controller: MikyUserBundle:Admin/Security:logout }

miky_user_admin_employee_security_login_check:
    path:      /login_check
    defaults:  { _controller: MikyUserBundle:Admin/Security:check }