miky_user_admin_user:
    resource: |
        alias: miky_user.user
        section: admin
        context: admin
        templates: MikyAdminBundle:Crud
        redirect: update
        grid: miky_user.admin.user
        form: miky_customer_admin
        permission: true
        vars:
            all:
                subheader: miky.ui.manage_customers
                templates:
                    #form: MikyAdminBundle:Product:_form.html.twig
            index:
                icon: cube
    type: miky.resource_admin