miky_user_admin_user:
    resource: |
        alias: miky_user.user
        section: admin
        context: admin
        templates: MikyAdminBundle:Crud
        redirect: update
        grid: miky_user.admin.user
        form: miky_user_admin
        permission: true
        vars:
            all:
                subheader: miky_user.manage_users
                templates:
                    #form: MikyAdminBundle:Product:_form.html.twig
            index:
                icon: cube
    type: miky.resource_admin
miky_user_admin_employee:
    resource: |
        alias: miky_user.employee
        section: admin
        context: admin
        templates: MikyAdminBundle:Crud
        redirect: update
        grid: miky_user.admin.employee
        form: miky_employee_admin
        permission: true
        vars:
            all:
                subheader: miky_user.manage_employees
                templates:
                    #form: MikyAdminBundle:Product:_form.html.twig
            index:
                icon: cube
    type: miky.resource_admin