<?php

namespace Miky\Bundle\UserBundle\Repository;

/**
 * CertificationRequestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CertificationRequestRepository extends \Doctrine\ORM\EntityRepository
{

    public function getCertificationPendingQueryBuilder(){
        $query = $this->createQueryBuilder('c')
            ->where('c.validated = false')
            ->where('c.pendingValidation = true');
        return $query;
    }
}
