<?php

namespace Miky\Bundle\UserBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CustomerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomerRepository extends EntityRepository
{
    public function getCertifiedQueryBuilder(){
        $query = $this->createQueryBuilder('c')
            ->where('c.certified = true');
        return $query;
    }
}
