<?php

namespace Miky\Bundle\UserBundle\Repository;

/**
 * UserReportRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserReportRepository extends \Doctrine\ORM\EntityRepository
{
}
