miky_resource:
    drivers:
        - doctrine/orm
    resources:
        miky.user:
            classes:
                model: %customer.model.class%
            contexts:
                admin:
                    controller: Miky\Bundle\UserBundle\Controller\Backend\CustomerAdminController
        miky.employee:
            classes:
                model: %employee.model.class%
            contexts:
                admin:
                    controller: Miky\Bundle\UserBundle\Controller\Backend\CustomerAdminController
        miky.user_report:
            classes:
                model: %user_report.entity.class%
            contexts:
                admin: ~
        miky.certification_request:
            classes:
                model: %certification_request.entity.class%
            contexts:
                admin:
                    controller: Miky\Bundle\UserBundle\Controller\Backend\CertificationRequestAdminController
miky_grid:
    grids:
        miky_user_admin_user:
            driver:
                options:
                    class: %customer.model.class%
            sorting:
                confirmedAt:
                    path: confirmedAt
                    direction: asc
            fields:
                email:
                    type: string
                    label: miky.ui.email
                username:
                    type: string
                    label: miky.ui.username
                enabled:
                    type: twig
                    label: miky.ui.enabled
                    options:
                        template: MikyAdminBundle:Grid/Field:enabled.html.twig
            filters:
                email:
                    type: string
                    label: miky.ui.email
                username:
                    type: string
                    label: miky.ui.username
                enabled:
                    type: boolean
                    label: miky.ui.enabled
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete

        miky_admin_customer_certified:
            driver:
                options:
                    class: %customer.model.class%
                    repository:
                        method: getCertifiedQueryBuilder
            sorting:
                confirmedAt:
                    path: confirmedAt
                    direction: asc
            fields:
                email:
                    type: string
                    label: miky.ui.email
                username:
                    type: string
                    label: miky.ui.username
                enabled:
                    type: twig
                    label: miky.ui.enabled
                    options:
                        template: MikyAdminBundle:Grid/Field:enabled.html.twig
            filters:
                email:
                    type: string
                    label: miky.ui.email
                username:
                    type: string
                    label: miky.ui.username
                enabled:
                    type: boolean
                    label: miky.ui.enabled
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete

        miky_admin_employee:
            driver:
                options:
                    class: %employee.model.class%
            sorting:
                confirmedAt:
                    path: confirmedAt
                    direction: asc
            fields:
                email:
                    type: string
                    label: miky.ui.email
                username:
                    type: string
                    label: miky.ui.username
                enabled:
                    type: twig
                    label: miky.ui.enabled
                    options:
                        template: MikyAdminBundle:Grid/Field:enabled.html.twig
            filters:
                email:
                    type: string
                    label: miky.ui.email
                username:
                    type: string
                    label: miky.ui.username
                enabled:
                    type: boolean
                    label: miky.ui.enabled
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete
        miky_user_report_admin:
            driver:
                options:
                    class: %user_report.entity.class%
            sorting:
                createdAt:
                    path: createdAt
                    direction: desc
            fields:
                whistleblower.username:
                    type: string
                    label: miky.ui.report_by
                reason:
                    type: string
                    label: miky.ui.reason
            filters:
#                title:
#                    type: string
#                    label: miky.ui.title
#                enabled:
#                    type: boolean
#                    label: miky.ui.enabled
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete

        miky_certification_request_admin:
            driver:
                options:
                    class: %certification_request.entity.class%
            sorting:
                createdAt:
                    path: createdAt
                    direction: desc
            fields:
                customer.username:
                    type: string
                    label: miky.ui.username
                comment:
                    type: string
                    label: miky.ui.comment
                companyId:
                    type: string
                    label: miky.ui.companyId
                validated:
                    type: twig
                    label: miky.ui.validated
                    options:
                        template: MikyAdminBundle:Grid/Field:enabled.html.twig
            filters:
                companyId:
                    type: string
                    label: miky.ui.companyId
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete

        miky_certification_request_pending_admin:
            driver:
                options:
                    class: %certification_request.entity.class%
                    repository:
                        method: getCertificationPendingQueryBuilder
            sorting:
                createdAt:
                    path: createdAt
                    direction: desc
            fields:
                customer.username:
                    type: string
                    label: miky.ui.username
                comment:
                    type: string
                    label: miky.ui.comment
                companyId:
                    type: string
                    label: miky.ui.companyId
                validated:
                    type: twig
                    label: miky.ui.validated
                    options:
                        template: MikyAdminBundle:Grid/Field:enabled.html.twig
            filters:
                companyId:
                    type: string
                    label: miky.ui.companyId
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete