miky_user_admin_security:
    resource: "@MikyUserBundle/Resources/config/routing/admin/security.yml"
    prefix : /%miky_admin.admin_path%

miky_user_admin_user:
    resource: |
        alias: miky_user.user
        section: admin
        context: admin
        templates: MikyAdminBundle:Crud
        redirect: update
        grid: miky_user.admin.user
        form: Miky\Bundle\UserBundle\Form\Type\Admin\UserAdminType
        permission: true
        vars:
            all:
                subheader: miky_user.manage_users
                templates:
                    #form: MikyAdminBundle:Product:_form.html.twig
            index:
                icon: cube
    type: miky.resource_admin
miky_user_admin_employee:
    resource: |
        alias: miky_user.employee
        section: admin
        context: admin
        templates: MikyAdminBundle:Crud
        redirect: update
        grid: miky_user.admin.employee
        form: Miky\Bundle\UserBundle\Form\Type\Admin\EmployeeAdminType
        permission: true
        vars:
            all:
                subheader: miky_user.manage_employees
                templates:
                    #form: MikyAdminBundle:Product:_form.html.twig
            index:
                icon: cube
    type: miky.resource_admin


