miky_admin_customer:
    resource: |
        alias: miky.customer
        section: admin
        context: admin
        templates: MikyAdminBundle:Crud
        redirect: update
        grid: miky_admin_customer
        form: miky_customer_admin
        permission: true
        vars:
            all:
                subheader: miky.ui.manage_customers
                templates:
                    #form: MikyAdminBundle:Product:_form.html.twig
            index:
                icon: cube
    type: miky.resource

miky_admin_certification_request:
    resource: |
        alias: miky.certification_request
        section: admin
        context: admin
        templates: MikyAdminBundle:Crud
        redirect: update
        grid: miky_certification_request_admin
        form: miky_certification_request_admin
        permission: true
        vars:
            all:
                subheader: miky.ui.manage_certification_request
                templates:
                    form: MikyUserBundle:Backend/Certification:_form.html.twig
            index:
                icon: cube
    type: miky.resource
miky_admin_certification_request_validate:
    path: /certification_request/{id}/validate
    methods: [GET]
    defaults:
        _controller: miky.controller.admin.certification_request:validateAction
        _miky:
            context: admin
miky_admin_certification_request_index_pending:
    path: /certification_request_pending
    methods: [GET]
    defaults:
        _controller: miky.controller.admin.certification_request:indexAction
        _miky:
            alias: miky.certification_request
            section: admin
            form: miky_certification_request_admin
            grid: miky_certification_request_pending_admin
            template: MikyAdminBundle:Crud:index.html.twig
            type: miky.resource

miky_admin_customer_index_certified:
    path: /customers_certified
    methods: [GET]
    defaults:
        _controller: miky.controller.admin.customer:indexAction
        _miky:
            alias: miky.customer
            section: admin
            form: miky_customer_admin
            grid: miky_admin_customer_certified
            template: MikyAdminBundle:Crud:index.html.twig
            type: miky.resource

miky_admin_employee:
    resource: |
        alias: miky.employee
        section: admin
        context: admin
        templates: MikyAdminBundle:Crud
        redirect: update
        grid: miky_admin_employee
        form: miky_employee_admin
        permission: true
        vars:
            all:
                subheader: miky.ui.manage_employees
                templates:
                    #form: MikyAdminBundle:Product:_form.html.twig
            index:
                icon: cube
    type: miky.resource

miky_admin_user_report:
    resource: |
        alias: miky.user_report
        section: admin
        context: admin
        templates: MikyAdminBundle:Crud
        redirect: update
        grid: miky_user_report_admin
        form: miky_user_report_admin
        permission: true
        vars:
            all:
                subheader: miky.ui.manage_user_report
            index:
                icon: cube
    type: miky.resource

