miky_app_customer_certification_request:
    path:      /request
    defaults:  { _controller: MikyUserBundle:Frontend/Certification:request }

miky_app_customer_certification_remove:
    path:      /remove/{certificationRequest}
    defaults:  { _controller: MikyUserBundle:Frontend/Certification:remove }

miky_app_customer_certification_pending:
    path:      /pending
    defaults:  { _controller: MikyUserBundle:Frontend/Certification:pending }



