miky_app_customer_history_list:
    path:      /list
    defaults:  { _controller: MikyUserBundle:Frontend/History:list}

miky_app_customer_history_remove:
    path:      /{history}/remove
    defaults:  { _controller: MikyUserBundle:Frontend/History:remove}
