#miky_user_front_profile:
#    resource: "@MikyUserBundle/Resources/config/routing/front/profile.yml"
#    prefix : /profile
#
miky_user_front_registration:
    resource: "@MikyUserBundle/Resources/config/routing/front/registration.yml"
    prefix : /registration

miky_user_front_resetting:
    resource: "@MikyUserBundle/Resources/config/routing/front/resetting.yml"
    prefix : /resetting

miky_user_front_security:
    resource: "@MikyUserBundle/Resources/config/routing/front/security.yml"
    prefix : /