miky_user_front_registration_register:
    path:      /
    defaults:  { _controller: MikyUserBundle:Front/Registration:register}

miky_user_front_registration_check_email:
    path:      /check-email
    defaults:  { _controller: MikyUserBundle:Front/Registration:checkEmail}

miky_user_front_registration_confirm:
    path:      /confirm/{token}
    defaults:  { _controller: MikyUserBundle:Front/Registration:confirm}

miky_user_front_registration_confirmed:
    path:      /confirmed
    defaults:  { _controller: MikyUserBundle:Front/Registration:confirmed}