miky_user_front_resetting_request:
    path:      /request
    defaults:  { _controller: MikyUserBundle:Frontend/Resetting:request}

miky_user_front_resetting_send_mail:
    path:      /send_mail
    defaults:  { _controller: MikyUserBundle:Frontend/Resetting:sendEmail}

miky_user_front_resetting_reset:
    path:      /{token}/reset
    defaults:  { _controller: MikyUserBundle:Frontend/Resetting:reset}

miky_user_front_resetting_check_email:
    path:      /check_email
    defaults:  { _controller: MikyUserBundle:Frontend/Resetting:checkEmail}


